desc_surfaces = {
    'Umurs_ext_avg': "coefficient de déperdition des murs donnant sur l'extérieur moyen (pondéré à la surface)",
    'Umurs_deper_avg': "coefficient de déperdition des murs donnant sur l'extérieur ou un local non chauffé moyen (pondéré à la surface)",
    'Uplancher_bas_deper_avg': "coefficient de déperdition des planchers bas ne donnant pas sur un logement mitoyen moyen (pondéré à la surface)",
    'Uplancher_haut_deper_avg': "coefficient de déperdition des planchers hauts ne donnant pas sur un logement mitoyen moyen (pondéré à la surface)",
    'is_plancher_bas_deper_isole': "booleen qui renseigne sur le status isolé ou non du plancher bas.",
    'is_plancher_haut_deper_isole': "booleen qui renseigne sur le status isolé ou non du plancher haut.",
    'is_murs_ext_isole': "booleen qui renseigne sur le status isolé ou non des murs donnant sur l'extérieur.",
    'is_murs_deper_isole': "booleen qui renseigne sur le status isolé ou non des murs donnant sur l'extérieur ou un local non chauffé.",
    'mat_murs_deper_top': "matériau principal des murs donnant sur l'extérieur ou un local non chauffé (avec la plus grande surface ) (matériau au sens de la TV004).",
    'mat_murs_ext_top': "matériau principal des murs donnants sur l'extérieur (avec la plus grande surface ) (matériau au sens de la TV004).",
    'mat_plancher_bas_deper_top': "matériau principal des planchers basne donnant pas sur un logement mitoyen(avec la plus grande surface associée ) (matériau au sens de la TV004).",
    'mat_plancher_haut_deper_top': "matériau principal des murs donnant sur l'extérieur ou un local non chauffé (avec la plus grande surface ) (matériau au sens de la TV004).",
    'Ubaie_avg': "coefficient de déperdition des baies donnant sur l'extérieur moyen (pondéré à la surface)",
    'type_vitrage_simple_top': 'type de vitrage principal (avec la plus grande surface associée ) (simple,double ou triple vitrage)',
    'orientation_concat': "concaténation des orientations des vitrages déclarés ex. Nord,Est,Ouest : vitrages sur les surfaces nord est et ouest.",
    'surf_murs_totale': 'surface de murs totale',
    'surf_murs_deper': 'surface de murs déperditive(extérieur + locaux non chauffés)',
    'surf_murs_ext': 'surface de murs extérieurs',
    'surf_pb_totale': 'surface de planchers bas totale',
    'surf_pb_deper': 'surface de planchers bas ne donnant pas sur un logement adjacent',
    'surf_ph_totale': 'surface de planchers hauts totale',
    'surf_ph_deper': 'surface de planchers hauts ne donnant pas sur un logement adjacent',
    'surface_vitree_totale': 'surface de paroi vitrée (fenêtre/porte fenêtre et parois vitrées)',
    'surface_porte_totale': 'surface de portes',
    'surfaces_vitree_orientee_est': 'surfaces vitrées orientées est',
    'surfaces_vitree_orientee_est_ou_ouest': 'surfaces vitrées orientées est ou ouest',
    'surfaces_vitree_orientee_horizontale': 'surfaces vitrées horizontales',
    'surfaces_vitree_orientee_nondef': 'surfaces vitrées avec orientation non définies',
    'surfaces_vitree_orientee_nord': 'surfaces vitrées orientées nord',
    'surfaces_vitree_orientee_ouest': 'surfaces vitrées orientées ouest',
    'surfaces_vitree_orientee_sud': 'surfaces vitrées orientées sud',
    'ratio_surface_vitree': 'ratio entre la surface vitrée totale et la surface de murs extérieurs.',
}

desc_td007_annexes={}

